#!/usr/bin/env bash
# Build-time generator for config.generated.js (Sentry DSN injection).
# Run before zipping the extension for the Chrome Web Store.
#
# Pulls DSN from env var BELLRING_EXTENSION_GLITCHTIP_DSN. The operator sources
# the value from Infisical:
#   main-host:/host-page/BELLRING_EXTENSION_GLITCHTIP_DSN
#
# Usage:
#   export BELLRING_EXTENSION_GLITCHTIP_DSN="$(infisical secrets get --plain ...)"
#   ./scripts/build-config.sh

set -euo pipefail

cd "$(dirname "$0")/.."

DSN="${BELLRING_EXTENSION_GLITCHTIP_DSN:-}"

if [[ -z "$DSN" ]]; then
  echo "[build-config] BELLRING_EXTENSION_GLITCHTIP_DSN not set; writing empty config (Sentry disabled)."
  cat > config.generated.js <<EOF
// Auto-generated by scripts/build-config.sh — DSN unset; Sentry will no-op.
self.__BELLRING_SENTRY_DSN__ = '';
EOF
else
  echo "[build-config] DSN present; writing config.generated.js."
  # Escape single quotes defensively.
  ESC_DSN=${DSN//\'/\\\'}
  cat > config.generated.js <<EOF
// Auto-generated by scripts/build-config.sh — do not commit.
self.__BELLRING_SENTRY_DSN__ = '${ESC_DSN}';
EOF
fi

echo "[build-config] wrote config.generated.js"
